services:
  installer:
    build: .
    environment:
      - DOCKER_ACTIVE=true
    volumes:
      - ./runner.sh:/app/runner.sh
    container_name: installer
    networks:
      - installer-network
    command: sh -c "sleep 10000"

networks:
  installer-network:
